{{- if .Values.createExtraConfigsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.extraSecretConfigsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pgbouncer.password }}
  POSTGRESQL_PASSWORD: {{ .Values.pgbouncer.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.extraSecretConfigs }}
  {{- range $key, $value := .Values.extraSecretConfigs }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
