---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecretName }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.containerEnv }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- if .Values.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.tls.clientCert }}
  client_tls.cert: {{ .Values.tls.clientCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.clientKey }}
  client_tls.key: {{ .Values.tls.clientKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.clientCA }}
  client_tls.ca: {{ .Values.tls.clientCA | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.serverCert }}
  server_tls.cert: {{ .Values.tls.serverCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.serverKey }}
  server_tls.key: {{ .Values.tls.serverKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.serverCA }}
  server_tls.ca: {{ .Values.tls.serverCA | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.configurationFile.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecretName }}-file
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  pgbouncer.ini: {{ .Values.configurationFile.configurationFileContent | b64enc | quote }}
  userlist.txt: {{ .Values.configurationFile.userListContent | b64enc | quote }}
{{- end }}
